apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  - "extensions"
  - "*"
  resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  - services/proxy
  - ingresses
  - endpoints
  - pods
  - pods/proxy
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs:
  - "*"
  verbs: ["get"]