resources:
- volume-claim.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- name: grafana-config
  files:
  - config/grafana.ini
  
generatorOptions:
  disableNameSuffixHash: true