apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
    name: service
  - port: 80
    protocol: TCP
    targetPort: 15672
    name: management
  - port: 15672
    protocol: TCP
    targetPort: 15672
    name: management-default
  selector:
    app: rabbitmq
