apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter-service
  labels:
    app: rabbitmq-exporter
spec:
  ports:
  - port: 9419
    protocol: TCP
    targetPort: 9419
    name: service
  selector:
    app: rabbitmq-exporter
